[package]
name = "pix"
version = "0.1.0"
authors = ["Mason Larobina <masonl@google.com>"]
edition = "2018"

[dependencies]
piston = "0.40.0"
piston_window = "0.87.0"
wayland-client = "0.21.11"
image = "0.21.0"
resize = "0.3.0"
walkdir = "2.2.7"
log = "0.4.6"
env_logger = "0.6.0"
crossbeam-channel = "0.3.6"
num_cpus = "1.9.0"
boolinator = "2.4.0"
clap = "2.32.0"
rocksdb = "0.11.0"
bincode = "1.0.1"
serde = "1.0.85"
serde_derive = "1.0.85"
histogram = "0.6.9"
lazy_static = "1.2.0"
dirs = "1.0.4"
failure = "*"
